created new branch AlgosOctWeek5
Serkebaeva/Algorithms pull request #3
Opened 2024-11-07 06:44 UTC by Serkebaeva

new branch  algosOctWeek5

2024-11-08 16:32 UTC, asanaliev requested changes
Also, please read Google Java Style Guide and apply their rules in your code.

2024-11-08 16:32 UTC, asanaliev commented on src/main/java/org/algorithms/ContainsDuplicate.java
> +        Arrays.sort(nums);
Can you do it without sorting?

2024-11-08 16:32 UTC, asanaliev commented on src/main/java/org/algorithms/ContainsDuplicate.java
> +        while(temp > 0) {
Replace `while` with `for` not to use extra temp variable. Using an internal var inside `for` is ok.

2024-11-08 16:32 UTC, asanaliev commented on src/main/java/org/algorithms/IndexOfFirstOccurrenceInAString.java
> +            return haystack.indexOf(needle);
Don't use ready method. Implement it yourself. Assume there is no `indexOf` ready.

2024-11-08 16:32 UTC, asanaliev commented on src/main/java/org/algorithms/PalindromeNumber.java
> Could you solve it without converting the integer to a string?

2024-11-19 15:01 UTC, Serkebaeva commented on src/main/java/org/algorithms/ContainsDuplicate.java
> +        Arrays.sort(nums);
@asanaliev  Contains duplicate: changed to For loop, without sorting, and Google Java Style Guide changed indentation to 2 in JVM, classes UpperCamelCased, methods lowerCamelCased, added vertical whitespaces for readability sake, am I missing anything here?

2024-11-19 17:30 UTC, asanaliev requested changes

2024-11-19 17:30 UTC, asanaliev commented on src/main/java/org/algorithms/ContainsDuplicate.java
> +    for (int i = 0; i < nums.length; i++) {
Works but using two loops is very inefficient. Try to solve using Set or Map, and one loop only.

2024-11-21 08:27 UTC, Serkebaeva commented on src/main/java/org/algorithms/ContainsDuplicate.java
> +    for (int i = 0; i < nums.length; i++) {
@asanaliev done

2024-11-21 13:07 UTC, asanaliev approved these changes
Let's merge the PR.

2024-11-21 16:52 UTC, merged